services:
  - type: web
    name: alphacore-tech
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production
