/**
 * AI Modals Page — txt2img & img2img via Modal.run endpoints
 * Disclaimer-gated, tabbed interface, desktop + mobile compatible.
 */
import { createElement } from '../components/utils.js';
import { buildPinPad } from '../components/pinpad.js';
import { logAction } from '../components/logger.js';

const LORA_OPTIONS = `
  <option value="none">NONE (BASE MODEL ONLY)</option>
  <option value="cunny">CUNNY</option>
  <option value="custom_training">CUSTOM</option>
  <option value="lora3">LORA SLOT 3 (PENDING)</option>
`;

function getModalSettings() {
  const defaults = {
    txt2imgUrl: 'https://ai-alphacore-tech--text-to-image-sdxl-merger-inference-web.modal.run/',
    img2imgUrl: 'https://ai-alphacore-tech--img2img-qwen-edit-plus-model-web.modal.run/',
    negativePrompt: 'worst quality, low quality, normal quality, lowres, monochrome, grayscale, watermark, signature, text, bad anatomy, bad hands, missing fingers, extra digit, deformed, ugly, mutated, distorted, pixelated, jpeg artifacts',
    guidanceScale: '7.0',
    guidanceImg: 4.0,
    stepsFastTxt: 10,
    stepsNormalTxt: 20,
    stepsFocusedTxt: 50,
    stepsFastImg: 8,
    stepsNormalImg: 17,
    stepsFocusedImg: 30
  };
  try {
    const custom = localStorage.getItem('alphacore_modal_settings');
    if (custom) {
      return { ...defaults, ...JSON.parse(custom) };
    }
  } catch (e) {
    console.error(e);
  }
  return defaults;
}

/* ─── DISCLAIMER SCREEN ─────────────────────────────────────── */
function buildDisclaimer(onAccept) {
  const wrap = document.createElement('div');
  wrap.className = 'aim-disclaimer-wrap';
  wrap.innerHTML = `
    <div class="aim-disclaimer-box">
      <div class="aim-disc-icon">⚠</div>
      <div class="aim-disc-title">// CONTENT_ADVISORY</div>
      <div class="aim-disc-badge">LEGAL DISCLAIMER</div>
      <div class="aim-disc-body">
        <p>The AI generation tools accessible through this interface are provided for <strong>creative and personal use only</strong>. By proceeding, you acknowledge and agree to the following:</p>
        <ul>
          <li>You are solely responsible for all content you generate.</li>
          <li>Generated content must comply with all applicable local, national, and international laws.</li>
          <li>You will not use these tools to generate content that depicts minors in any sexual or harmful context.</li>
          <li>You will not use these tools to generate non-consensual imagery, defamatory content, or material intended to harass or harm any individual.</li>
          <li>The operator of this platform assumes no liability for content generated by users.</li>
          <li>Misuse may result in permanent access revocation and legal action.</li>
        </ul>
        <p class="aim-disc-warning">By clicking <strong>ACCEPT &amp; PROCEED</strong> you confirm you are 18 years of age or older and agree to use these tools responsibly and lawfully.</p>
      </div>
      <div class="aim-disc-actions">
        <button class="aim-btn aim-btn-accept" id="disc-accept">ACCEPT &amp; PROCEED</button>
        <button class="aim-btn aim-btn-decline" id="disc-decline">DECLINE</button>
      </div>
    </div>
  `;
  wrap.querySelector('#disc-accept').onclick = () => {
    sessionStorage.setItem('aim_disclaimer_accepted', '1');
    onAccept();
  };
  wrap.querySelector('#disc-decline').onclick = () => {
    window.location.hash = '#/';
  };
  return wrap;
}

/* ─── LOADING OVERLAY ───────────────────────────────────────── */
function buildLoader(text = 'SYNTHESIZING...') {
  const el = document.createElement('div');
  el.className = 'aim-loader';
  el.innerHTML = `
    <div class="aim-loader-inner">
      <div class="aim-spinner"></div>
      <div class="aim-loader-text" id="aim-loader-text">${text}</div>
      <div class="aim-loader-sub">MODAL GPU ACTIVE — PLEASE WAIT</div>
      <div class="aim-progress-wrap" style="width: 100%; height: 6px; background: rgba(255,255,255,0.1); margin-top: 15px; border-radius: 3px; overflow: hidden; display: none;">
        <div class="aim-progress-bar" id="aim-progress-bar" style="width: 0%; height: 100%; background: var(--accent, #ff003c); transition: width 0.2s; box-shadow: 0 0 8px var(--accent, #ff003c);"></div>
      </div>
    </div>
  `;
  return el;
}

function updateProgress(loader, step, maxSteps) {
  const wrap = loader.querySelector('.aim-progress-wrap');
  const bar = loader.querySelector('.aim-progress-bar');
  if (wrap && bar) {
    wrap.style.display = 'block';
    const pct = Math.min(100, Math.round(((step + 1) / maxSteps) * 100));
    bar.style.width = `${pct}%`;
  }
}

/* ─── RESULT PANEL ──────────────────────────────────────────── */
function buildResult(urls = []) {
  const el = document.createElement('div');
  el.className = 'aim-result hidden';
  if (!Array.isArray(urls)) urls = [urls];
  if (urls.length === 0) return el;
  let currentIdx = 0;

  el.innerHTML = `
    <div class="aim-result-label" style="display:flex; justify-content:space-between; align-items:center; cursor:pointer;" id="aim-result-toggle">
      <span>// OUTPUT_ARTIFACT</span>
      <div>
        <span class="aim-batch-count" style="opacity:0.7; margin-right:10px;">${urls.length > 1 ? '1 / ' + urls.length : ''}</span>
        <span id="aim-result-toggle-icon">▼</span>
      </div>
    </div>
    <div id="aim-result-content-area">
      <div class="aim-result-img-wrap">
        <img class="aim-result-img" id="aim-result-img" src="${urls[0]}" alt="Generated output" />
      </div>
      <div class="aim-result-actions" style="display:flex; justify-content:space-between; align-items:center;">
        <div class="aim-batch-nav" style="display:${urls.length > 1 ? 'flex' : 'none'}; gap:10px;">
          <button class="aim-btn aim-btn-dl" id="aim-prev-btn">◀ PREV</button>
          <button class="aim-btn aim-btn-dl" id="aim-next-btn">NEXT ▶</button>
        </div>
        <button class="aim-btn aim-btn-dl" id="aim-dl-btn">⬇ DOWNLOAD</button>
      </div>
    </div>
  `;

  // Toggle collapsibility
  el.querySelector('#aim-result-toggle').onclick = () => {
    const area = el.querySelector('#aim-result-content-area');
    const icon = el.querySelector('#aim-result-toggle-icon');
    if (area.style.display === 'none') {
      area.style.display = 'block';
      icon.textContent = '▼';
    } else {
      area.style.display = 'none';
      icon.textContent = '▶';
    }
  };

  if (urls.length > 1) {
    const imgEl = el.querySelector('#aim-result-img');
    const countEl = el.querySelector('.aim-batch-count');
    
    el.querySelector('#aim-prev-btn').onclick = () => {
      currentIdx = (currentIdx - 1 + urls.length) % urls.length;
      imgEl.src = urls[currentIdx];
      countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
    };
    
    el.querySelector('#aim-next-btn').onclick = () => {
      currentIdx = (currentIdx + 1) % urls.length;
      imgEl.src = urls[currentIdx];
      countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
    };
  }

  el.querySelector('#aim-dl-btn').onclick = () => {
    const a = document.createElement('a');
    a.href = urls[currentIdx];
    a.download = `alphacore_output_${Date.now()}_${currentIdx}.png`;
    a.click();
  };

  return el;
}

/* ─── TXT2IMG PANEL ─────────────────────────────────────────── */
function buildTxt2Img() {
  const settings = getModalSettings();
  const wrap = document.createElement('div');
  wrap.className = 'aim-panel';
  wrap.innerHTML = `
    <div class="aim-panel-header">
      <span class="aim-panel-icon">✦</span>
      <span class="aim-panel-title">TEXT TO IMAGE</span>
      <span class="aim-panel-badge">SDXL MERGER</span>
    </div>

    <div class="aim-field">
      <label class="aim-label" for="t2i-prompt">PROMPT MATRIX</label>
      <textarea class="aim-textarea" id="t2i-prompt" rows="4" placeholder="Describe what you want to generate..."></textarea>
    </div>

    <div class="aim-row">
      <div class="aim-field aim-field-half">
        <label class="aim-label">SPEED MODE</label>
        <div class="aim-seg aim-seg-3" id="t2i-speed">
          <button class="aim-seg-btn active" data-steps="${settings.stepsFastTxt}">⚡ FAST</button>
          <button class="aim-seg-btn" data-steps="${settings.stepsNormalTxt}">⚖ NORMAL</button>
          <button class="aim-seg-btn" data-steps="${settings.stepsFocusedTxt}">🎯 FOCUSED</button>
        </div>
      </div>
      <div class="aim-field aim-field-half">
        <label class="aim-label">BASE MODEL</label>
        <div class="aim-seg aim-seg-3" id="t2i-model">
          <button class="aim-seg-btn active" data-j="1" data-c="0">JUGGERNAUT</button>
          <button class="aim-seg-btn" data-j="0" data-c="1">CYBERREAL</button>
          <button class="aim-seg-btn" data-j="1" data-c="1">MERGED</button>
        </div>
      </div>
    </div>

    <div class="aim-row">
      <div class="aim-field aim-field-half">
        <label class="aim-label" for="t2i-batch">BATCH COUNT (1-4)</label>
        <input class="aim-input" type="number" id="t2i-batch" min="1" max="4" value="1" />
      </div>
        <div class="aim-field" id="t2i-lora-field" style="display: ${sessionStorage.getItem('lora_authenticated') ? 'block' : 'none'};">
          <label class="aim-label" for="t2i-lora">ACTIVE LORAS (CTRL+CLICK) ${sessionStorage.getItem('darkness_mode_active') !== 'true' ? '<span style="color:#ff003c; margin-left:4px;">[LOCKED]</span>' : ''}</label>
          <select class="aim-input aim-lora-select" id="t2i-lora" multiple ${sessionStorage.getItem('darkness_mode_active') === 'true' ? '' : 'disabled'}>
            ${LORA_OPTIONS}
          </select>
        </div>
    </div>

    <details class="aim-advanced">
      <summary class="aim-advanced-toggle">▶ ADVANCED PARAMETERS</summary>
      <div class="aim-advanced-body">
        <div class="aim-field">
          <label class="aim-label" for="t2i-neg">NEGATIVE PROMPT</label>
          <textarea class="aim-textarea aim-textarea-sm" id="t2i-neg" rows="2">${settings.negativePrompt}</textarea>
        </div>
        <div class="aim-field">
          <label class="aim-label" for="t2i-cfg">GUIDANCE SCALE <span class="aim-val-display" id="t2i-cfg-val">${parseFloat(settings.guidanceScale).toFixed(1)}</span></label>
          <input class="aim-range" type="range" id="t2i-cfg" min="1" max="15" step="0.5" value="${settings.guidanceScale}" />
        </div>
      </div>
    </details>

      <button class="aim-btn-generate" id="t2i-gen-btn" ${sessionStorage.getItem('generate_authenticated') ? '' : 'disabled'}>
        <span class="aim-btn-icon">⚡</span> ${sessionStorage.getItem('generate_authenticated') ? 'INITIALIZE SYNTHESIS' : 'ACCESS DENIED'}
      </button>

    <div class="aim-status-bar" id="t2i-status"></div>
    <div id="t2i-loader-slot"></div>
    <div id="t2i-result-slot"></div>
  `;

  // Wire up segment controls
  wrap.querySelectorAll('#t2i-speed .aim-seg-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      wrap.querySelectorAll('#t2i-speed .aim-seg-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });
  wrap.querySelectorAll('#t2i-model .aim-seg-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      wrap.querySelectorAll('#t2i-model .aim-seg-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });

  // CFG display
  const cfgInput = wrap.querySelector('#t2i-cfg');
  const cfgVal = wrap.querySelector('#t2i-cfg-val');
  cfgInput.addEventListener('input', () => { cfgVal.textContent = parseFloat(cfgInput.value).toFixed(1); });

  // Generate
  wrap.querySelector('#t2i-gen-btn').addEventListener('click', async () => {
    const prompt = wrap.querySelector('#t2i-prompt').value.trim();
    if (!prompt) { setStatus(wrap, '#t2i-status', 'ERROR: Prompt matrix is empty.', 'error'); return; }

    const steps = parseInt(wrap.querySelector('#t2i-speed .aim-seg-btn.active').dataset.steps);
    const modelBtn = wrap.querySelector('#t2i-model .aim-seg-btn.active');
    const j = modelBtn.dataset.j;
    const c = modelBtn.dataset.c;
    let neg = wrap.querySelector('#t2i-neg').value;
    const cfg = parseFloat(wrap.querySelector('#t2i-cfg').value).toFixed(1);
    const batchSize = parseInt(wrap.querySelector('#t2i-batch').value) || 1;
    const loraSelect = wrap.querySelector('#t2i-lora');
    let lora = '';
    if (loraSelect && !loraSelect.disabled) {
      lora = Array.from(loraSelect.selectedOptions).map(opt => opt.value).join(',');
    }

    // Check for darkness mode and override negative prompt
    if (sessionStorage.getItem('darkness_mode_active') === 'true') {
      neg = ''; // Override negative prompt, removing restrictions.
      console.warn('[DARKNESS] NSFW governors disabled for this T2I request.');
    }

    const loaderSlot = wrap.querySelector('#t2i-loader-slot');
    const resultSlot = wrap.querySelector('#t2i-result-slot');
    const genBtn = wrap.querySelector('#t2i-gen-btn');

    genBtn.disabled = true;
    setStatus(wrap, '#t2i-status', 'ROUTING TO GPU NODE...', 'info');
    resultSlot.innerHTML = '';
    const loader = buildLoader('SYNTHESIZING IMAGE...');
    loaderSlot.innerHTML = '';
    loaderSlot.appendChild(loader);

    const loaderMessages = ['SYNTHESIZING IMAGE...','DENOISING LATENTS...','RENDERING ARTIFACT...','FINALIZING OUTPUT...'];
    let msgIdx = 0;
    const msgInterval = setInterval(() => {
      msgIdx = (msgIdx + 1) % loaderMessages.length;
      const ltEl = loaderSlot.querySelector('#aim-loader-text');
      if (ltEl) ltEl.textContent = loaderMessages[msgIdx];
    }, 2500);

    try {
      const params = new URLSearchParams({
        prompt,
        JuggernautXL: j,
        CyberRealisticXL: c,
        negative_prompt: neg,
        guidance_scale: cfg,
        num_inference_steps: steps,
        batch_size: batchSize,
        lora: lora,
        scheduler: 'Euler',
        seed: -1,
      });
      const res = await fetch(`${settings.txt2imgUrl}stream?${params}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let url = null;

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        const lines = buffer.split('\n\n');
        buffer = lines.pop(); 

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const dataStr = line.substring(6);
            try {
              const data = JSON.parse(dataStr);
              if (data.step !== undefined && data.max_steps !== undefined) {
                updateProgress(loader, data.step, data.max_steps);
              } else if (data.image_b64) {
                const b64s = Array.isArray(data.image_b64) ? data.image_b64 : [data.image_b64];
                url = b64s.map(b64 => {
                  const byteCharacters = atob(b64);
                  const byteNumbers = new Array(byteCharacters.length);
                  for (let i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                  }
                  const byteArray = new Uint8Array(byteNumbers);
                  const blob = new Blob([byteArray], {type: 'image/png'});
                  return URL.createObjectURL(blob);
                });
              } else if (data.error) {
                throw new Error(data.error);
              }
            } catch (e) {
              if (e.message !== "Unexpected end of JSON input" && !e.message.includes('JSON')) {
                throw e; 
              }
            }
          }
        }
      }

      if (!url || url.length === 0) throw new Error("Stream finished but no image received");

      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';

      const resultEl = buildResult(url);
      resultEl.classList.remove('hidden');
      resultSlot.appendChild(resultEl);
      setStatus(wrap, '#t2i-status', 'ARTIFACT RENDERED SUCCESSFULLY.', 'ok');
      logAction('IMAGE_GENERATED', { type: 'T2I', prompt, batchSize });
    } catch (err) {
      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';
      setStatus(wrap, '#t2i-status', `FAILURE: ${err.message}`, 'error');
    } finally {
      genBtn.disabled = false;
    }
  });

  return wrap;
}

/* ─── IMG2IMG PANEL ─────────────────────────────────────────── */
function buildImg2Img() {
  const settings = getModalSettings();
  const wrap = document.createElement('div');
  wrap.className = 'aim-panel';
  wrap.innerHTML = `
    <div class="aim-panel-header">
      <span class="aim-panel-icon">⟁</span>
      <span class="aim-panel-title">IMAGE TO IMAGE</span>
      <span class="aim-panel-badge">QWEN EDIT+</span>
    </div>

    <div class="aim-field">
      <label class="aim-label">INPUT IMAGE</label>
      <div class="aim-dropzone" id="i2i-dropzone">
        <input type="file" id="i2i-file" accept="image/*" class="aim-file-input" />
        <div class="aim-dropzone-inner" id="i2i-dz-inner">
          <div class="aim-dz-icon">📁</div>
          <div class="aim-dz-text">DROP IMAGE HERE or <span class="aim-dz-link">BROWSE</span></div>
          <div class="aim-dz-sub">PNG, JPG, WEBP — max 10MB</div>
        </div>
        <img class="aim-dz-preview hidden" id="i2i-preview" alt="preview" />
      </div>
    </div>

    <div class="aim-field">
      <label class="aim-label" for="i2i-prompt">EDIT INSTRUCTION</label>
      <textarea class="aim-textarea" id="i2i-prompt" rows="3" placeholder="Describe the edits you want applied to the image..."></textarea>
    </div>

    <div class="aim-field">
      <label class="aim-label">PROCESSING MODE</label>
      <div class="aim-seg aim-seg-3" id="i2i-speed">
        <button class="aim-seg-btn active" data-steps="${settings.stepsFastImg}">⚡ FAST</button>
        <button class="aim-seg-btn" data-steps="${settings.stepsNormalImg}">⚖ NORMAL</button>
        <button class="aim-seg-btn" data-steps="${settings.stepsFocusedImg}">🎯 FOCUSED</button>
      </div>
    </div>

    <div class="aim-row">
      <div class="aim-field aim-field-half">
        <label class="aim-label" for="i2i-batch">BATCH COUNT (1-4)</label>
        <input class="aim-input" type="number" id="i2i-batch" min="1" max="4" value="1" />
      </div>
        <div class="aim-field" id="i2i-lora-field" style="display: ${sessionStorage.getItem('lora_authenticated') ? 'block' : 'none'};">
          <label class="aim-label" for="i2i-lora">ACTIVE LORAS (CTRL+CLICK) ${sessionStorage.getItem('darkness_mode_active') !== 'true' ? '<span style="color:#ff003c; margin-left:4px;">[LOCKED]</span>' : ''}</label>
          <select class="aim-input aim-lora-select" id="i2i-lora" multiple ${sessionStorage.getItem('darkness_mode_active') === 'true' ? '' : 'disabled'}>
            ${LORA_OPTIONS}
          </select>
        </div>
    </div>

    <details class="aim-advanced">
      <summary class="aim-advanced-toggle">▶ ADVANCED PARAMETERS</summary>
      <div class="aim-advanced-body">
        <div class="aim-field">
          <label class="aim-label" for="i2i-neg">NEGATIVE PROMPT</label>
          <textarea class="aim-textarea aim-textarea-sm" id="i2i-neg" rows="2">${settings.negativePrompt}</textarea>
        </div>
        <div class="aim-field" style="margin-top: 12px;">
          <label class="aim-label" for="i2i-cfg">GUIDANCE SCALE <span class="aim-val-display" id="i2i-cfg-val">${parseFloat(settings.guidanceImg).toFixed(1)}</span></label>
          <input class="aim-range" type="range" id="i2i-cfg" min="1" max="15" step="0.5" value="${settings.guidanceImg}" />
        </div>
      </div>
    </details>

    <button class="aim-btn aim-btn-generate" id="i2i-gen-btn" ${sessionStorage.getItem('generate_authenticated') ? '' : 'disabled'}>
      <span class="aim-btn-icon">⚡</span> ${sessionStorage.getItem('generate_authenticated') ? 'INITIATE EDIT' : 'ACCESS DENIED'}
    </button>

    <div class="aim-status-bar" id="i2i-status"></div>
    <div id="i2i-loader-slot"></div>
    <div id="i2i-result-slot"></div>
  `;

  // Speed selector
  wrap.querySelectorAll('#i2i-speed .aim-seg-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      wrap.querySelectorAll('#i2i-speed .aim-seg-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });

  // Guidance scale display
  const i2iCfgInput = wrap.querySelector('#i2i-cfg');
  const i2iCfgVal = wrap.querySelector('#i2i-cfg-val');
  if (i2iCfgInput && i2iCfgVal) {
    i2iCfgInput.addEventListener('input', () => {
      i2iCfgVal.textContent = parseFloat(i2iCfgInput.value).toFixed(1);
    });
  }

  // File input / dropzone
  const fileInput = wrap.querySelector('#i2i-file');
  const dropzone = wrap.querySelector('#i2i-dropzone');
  const dzInner = wrap.querySelector('#i2i-dz-inner');
  const preview = wrap.querySelector('#i2i-preview');

  function showPreview(file) {
    if (!file) return;
    const url = URL.createObjectURL(file);
    preview.src = url;
    preview.classList.remove('hidden');
    dzInner.classList.add('hidden');
    dropzone.classList.add('has-preview');
  }

  fileInput.addEventListener('change', () => { if (fileInput.files[0]) showPreview(fileInput.files[0]); });
  dropzone.addEventListener('click', e => {
    if (e.target === fileInput || e.target.classList.contains('aim-dz-preview')) return;
    fileInput.click();
  });
  dropzone.addEventListener('dragover', e => { e.preventDefault(); dropzone.classList.add('drag-over'); });
  dropzone.addEventListener('dragleave', () => dropzone.classList.remove('drag-over'));
  dropzone.addEventListener('drop', e => {
    e.preventDefault();
    dropzone.classList.remove('drag-over');
    const file = e.dataTransfer.files[0];
    if (file && file.type.startsWith('image/')) { fileInput._droppedFile = file; showPreview(file); }
  });

  // Generate
  wrap.querySelector('#i2i-gen-btn').addEventListener('click', async () => {
    const file = fileInput._droppedFile || fileInput.files[0];
    if (!file) { setStatus(wrap, '#i2i-status', 'ERROR: No input image loaded.', 'error'); return; }
    const prompt = wrap.querySelector('#i2i-prompt').value.trim();
    if (!prompt) { setStatus(wrap, '#i2i-status', 'ERROR: Edit instruction is empty.', 'error'); return; }

    const steps = parseInt(wrap.querySelector('#i2i-speed .aim-seg-btn.active').dataset.steps);
    let neg = wrap.querySelector('#i2i-neg').value;
    const cfg = parseFloat(wrap.querySelector('#i2i-cfg').value).toFixed(1);
    const batchSize = parseInt(wrap.querySelector('#i2i-batch').value) || 1;
    const loraSelect = wrap.querySelector('#i2i-lora');
    let lora = '';
    if (loraSelect && !loraSelect.disabled) {
      lora = Array.from(loraSelect.selectedOptions).map(opt => opt.value).join(',');
    }
    
    // Check for darkness mode and override negative prompt
    if (sessionStorage.getItem('darkness_mode_active') === 'true') {
      neg = ''; // Override negative prompt, removing restrictions.
      console.warn('[DARKNESS] NSFW governors disabled for this I2I request.');
    }

    const loaderSlot = wrap.querySelector('#i2i-loader-slot');
    const resultSlot = wrap.querySelector('#i2i-result-slot');
    const genBtn = wrap.querySelector('#i2i-gen-btn');

    genBtn.disabled = true;
    setStatus(wrap, '#i2i-status', 'ROUTING TO GPU NODE...', 'info');
    resultSlot.innerHTML = '';
    const loader = buildLoader('PROCESSING EDIT...');
    loaderSlot.innerHTML = '';
    loaderSlot.appendChild(loader);

    const loaderMessages = ['PROCESSING EDIT...','APPLYING INSTRUCTION...','DIFFUSING CHANGES...','RENDERING OUTPUT...'];
    let msgIdx = 0;
    const msgInterval = setInterval(() => {
      msgIdx = (msgIdx + 1) % loaderMessages.length;
      const ltEl = loaderSlot.querySelector('#aim-loader-text');
      if (ltEl) ltEl.textContent = loaderMessages[msgIdx];
    }, 2500);

    try {
      const formData = new FormData();
      formData.append('image', file);
      formData.append('prompt', prompt);
      formData.append('negative_prompt', neg);
      formData.append('num_inference_steps', steps);
      formData.append('true_cfg_scale', cfg);
      formData.append('batch_size', batchSize);
      formData.append('lora', lora);
      formData.append('seed', -1);

      const res = await fetch(`${settings.img2imgUrl}stream`, { method: 'POST', body: formData });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let url = null;

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        const lines = buffer.split('\n\n');
        buffer = lines.pop(); 

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const dataStr = line.substring(6);
            try {
              const data = JSON.parse(dataStr);
              if (data.step !== undefined && data.max_steps !== undefined) {
                updateProgress(loader, data.step, data.max_steps);
              } else if (data.image_b64) {
                const b64s = Array.isArray(data.image_b64) ? data.image_b64 : [data.image_b64];
                url = b64s.map(b64 => {
                  const byteCharacters = atob(b64);
                  const byteNumbers = new Array(byteCharacters.length);
                  for (let i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                  }
                  const byteArray = new Uint8Array(byteNumbers);
                  const blob = new Blob([byteArray], {type: 'image/png'});
                  return URL.createObjectURL(blob);
                });
              } else if (data.error) {
                throw new Error(data.error);
              }
            } catch (e) {
              if (e.message !== "Unexpected end of JSON input" && !e.message.includes('JSON')) {
                throw e; 
              }
            }
          }
        }
      }

      if (!url || url.length === 0) throw new Error("Stream finished but no image received");

      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';

      const resultEl = buildResult(url);
      resultEl.classList.remove('hidden');
      resultSlot.appendChild(resultEl);
      setStatus(wrap, '#i2i-status', 'EDIT APPLIED SUCCESSFULLY.', 'ok');
      logAction('IMAGE_GENERATED', { type: 'I2I', prompt, batchSize });
    } catch (err) {
      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';
      setStatus(wrap, '#i2i-status', `FAILURE: ${err.message}`, 'error');
    } finally {
      genBtn.disabled = false;
    }
  });

  return wrap;
}

/* ─── HELPERS ────────────────────────────────────────────────── */
function setStatus(root, sel, msg, type = '') {
  const el = root.querySelector(sel);
  if (!el) return;
  el.textContent = `> ${msg}`;
  el.className = 'aim-status-bar' + (type ? ` aim-status-${type}` : '');
}

/* ─── MAIN PAGE ─────────────────────────────────────────────── */
export default function AiModals() {
  const container = createElement('div', { class: 'aimodals-page' });

  function showNextStep() {
    container.innerHTML = '';
    // If disclaimer not accepted this session, show it first
    if (!sessionStorage.getItem('aim_disclaimer_accepted')) {
      container.appendChild(buildDisclaimer(() => {
        container.innerHTML = '';
        container.appendChild(buildMainUI());
      }));
    } else {
      container.appendChild(buildMainUI());
    }
  }

  if (!sessionStorage.getItem('aimodals_authenticated')) {
    container.appendChild(buildPinPad({
      authKey: 'aimodals_authenticated',
      requiredRole: 'aimodals',
      onSuccess: showNextStep,
      title: '// SECURITY_LOCKOUT',
      subtitle: 'UNRESTRICTED GENERATION ACCESS',
      icon: '🔒'
    }));
  } else {
    showNextStep();
  }

  return container;
}


function buildMainUI() {
  const root = document.createElement('div');
  root.className = 'aim-root';
  root.innerHTML = `
    <div class="aim-header">
      <div class="aim-header-badge">[SYS_MODULE] // GENERATIVE_AI</div>
      <h1 class="glitch aim-title" data-text="AI MODALS // SYNTHESIS_ENGINE">AI MODALS // SYNTHESIS_ENGINE</h1>
      <div class="header-line"></div>
      <p class="aim-subtitle">Neural image synthesis via Modal GPU infrastructure. Select a generation mode below.</p>
    </div>

    <div class="aim-tabs" id="aim-tabs">
      <button class="aim-tab active" data-tab="txt2img" id="aim-tab-t2i">
        <span class="aim-tab-icon">✦</span> TXT2IMG
      </button>
      <button class="aim-tab" data-tab="img2img" id="aim-tab-i2i">
        <span class="aim-tab-icon">⟁</span> IMG2IMG
      </button>
    </div>

    <div id="aim-content"></div>
  `;

  const content = root.querySelector('#aim-content');
  const tabs = root.querySelectorAll('.aim-tab');

  let currentPanel = buildTxt2Img();
  content.appendChild(currentPanel);

  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => t.classList.remove('active'));
      tab.classList.add('active');
      content.innerHTML = '';
      if (tab.dataset.tab === 'txt2img') {
        currentPanel = buildTxt2Img();
      } else {
        currentPanel = buildImg2Img();
      }
      content.appendChild(currentPanel);
    });
  });

  return root;
}