/**
 * AI Modals Page — txt2img & img2img via Modal.run endpoints
 * Disclaimer-gated, tabbed interface, desktop + mobile compatible.
 */
import { createElement } from '../components/utils.js';
import { buildPinPad, requireAuth } from '../components/pinpad.js';
import { saveImageToGallery } from '../components/vision_db.js';
import { logAction } from '../components/logger.js';

const LORA_OPTIONS = `
  <option value="none">NONE (BASE MODEL ONLY)</option>
  <option value="New_Amateurs_XL.safetensors">AMATEUR</option>
`;

function getModalSettings() {
  const defaults = {
    txt2imgUrl: 'https://ai-alphacore-tech--text-to-image-sdxl-merger-inference-web.modal.run/',
    img2imgUrl: 'https://ai-alphacore-tech--img2img-qwen-edit-plus-model-web.modal.run/',
    negativePrompt: 'worst quality, low quality, normal quality, lowres, monochrome, grayscale, watermark, signature, text, bad anatomy, bad hands, missing fingers, extra digit, deformed, ugly, mutated, distorted, pixelated, jpeg artifacts',
    guidanceScale: '7.0',
    guidanceImg: 4.0,
    stepsFastTxt: 10,
    stepsNormalTxt: 20,
    stepsFocusedTxt: 50,
    stepsFastImg: 8,
    stepsNormalImg: 17,
    stepsFocusedImg: 30
  };
  try {
    const custom = localStorage.getItem('alphacore_modal_settings');
    if (custom) {
      return { ...defaults, ...JSON.parse(custom) };
    }
  } catch (e) {
    console.error(e);
  }
  return defaults;
}

/* ─── DISCLAIMER SCREEN ─────────────────────────────────────── */
function buildDisclaimer(onAccept) {
  const wrap = document.createElement('div');
  wrap.className = 'aim-disclaimer-wrap';
  wrap.innerHTML = `
    <div class="aim-disclaimer-box">
      <div class="aim-disc-icon">⚠</div>
      <div class="aim-disc-title">// CONTENT_ADVISORY</div>
      <div class="aim-disc-badge">LEGAL DISCLAIMER</div>
      <div class="aim-disc-body">
        <p>The AI generation tools accessible through this interface are provided for <strong>creative and personal use only</strong>. By proceeding, you acknowledge and agree to the following:</p>
        <ul>
          <li>You are solely responsible for all content you generate.</li>
          <li>Generated content must comply with all applicable local, national, and international laws.</li>
          <li>You will not use these tools to generate content that depicts minors in any sexual or harmful context.</li>
          <li>You will not use these tools to generate non-consensual imagery, defamatory content, or material intended to harass or harm any individual.</li>
          <li>The operator of this platform assumes no liability for content generated by users.</li>
          <li>Misuse may result in permanent access revocation and legal action.</li>
        </ul>
        <p class="aim-disc-warning">By clicking <strong>ACCEPT &amp; PROCEED</strong> you confirm you are 18 years of age or older and agree to use these tools responsibly and lawfully.</p>
      </div>
      <div class="aim-disc-actions">
        <button class="aim-btn aim-btn-accept" id="disc-accept">ACCEPT &amp; PROCEED</button>
        <button class="aim-btn aim-btn-decline" id="disc-decline">DECLINE</button>
      </div>
    </div>
  `;
  wrap.querySelector('#disc-accept').onclick = () => {
    sessionStorage.setItem('aim_disclaimer_accepted', '1');
    onAccept();
  };
  wrap.querySelector('#disc-decline').onclick = () => {
    window.location.hash = '#/';
  };
  return wrap;
}

/* ─── LOADING OVERLAY ───────────────────────────────────────── */
function buildLoader(text = 'SYNTHESIZING...') {
  const el = document.createElement('div');
  el.className = 'aim-loader';
  el.innerHTML = `
    <div class="aim-loader-inner">
      <div class="aim-spinner"></div>
      <div class="aim-loader-text" id="aim-loader-text">${text}</div>
      <div class="aim-loader-sub">MODAL GPU ACTIVE — PLEASE WAIT</div>
      <div class="aim-progress-wrap" style="width: 100%; height: 6px; background: rgba(255,255,255,0.1); margin-top: 15px; border-radius: 3px; overflow: hidden; display: none;">
        <div class="aim-progress-bar" id="aim-progress-bar" style="width: 0%; height: 100%; background: var(--accent, #ff003c); transition: width 0.2s; box-shadow: 0 0 8px var(--accent, #ff003c);"></div>
      </div>
    </div>
  `;
  return el;
}

function updateProgress(loader, step, maxSteps) {
  const wrap = loader.querySelector('.aim-progress-wrap');
  const bar = loader.querySelector('.aim-progress-bar');
  if (wrap && bar) {
    wrap.style.display = 'block';
    const pct = Math.min(100, Math.round(((step + 1) / maxSteps) * 100));
    bar.style.width = `${pct}%`;
  }
}

/* ─── RESULT PANEL ──────────────────────────────────────────── */
function buildResult(urls = []) {
  const el = document.createElement('div');
  el.className = 'aim-result hidden';
  if (!Array.isArray(urls)) urls = [urls];
  if (urls.length === 0) return el;
  let currentIdx = 0;

  el.innerHTML = `
    <div class="aim-result-label" style="display:flex; justify-content:space-between; align-items:center; cursor:pointer;" id="aim-result-toggle">
      <span>// OUTPUT_ARTIFACT</span>
      <div>
        <span class="aim-batch-count" style="opacity:0.7; margin-right:10px;">${urls.length > 1 ? '1 / ' + urls.length : ''}</span>
        <span id="aim-result-toggle-icon">▼</span>
      </div>
    </div>
    <div id="aim-result-content-area">
      <div class="aim-result-img-wrap">
        <img class="aim-result-img" id="aim-result-img" src="${urls[0]}" alt="Generated output" />
      </div>
      <div class="aim-result-actions" style="display:flex; justify-content:space-between; align-items:center;">
        <div class="aim-batch-nav" style="display:${urls.length > 1 ? 'flex' : 'none'}; gap:6px; align-items:center;">
          <button class="aim-btn aim-btn-dl" id="aim-prev-btn">◀ PREV</button>
          <button class="aim-btn aim-btn-dl" id="aim-slideshow-btn" title="Toggle Auto Slideshow">▶ AUTO</button>
          <button class="aim-btn aim-btn-dl" id="aim-next-btn">NEXT ▶</button>
        </div>
        <div style="display:flex; gap:10px;">
          ${urls.length > 1 ? `<button class="aim-btn aim-btn-dl" id="aim-dl-all-btn">⬇ DOWN ALL</button>` : ''}
          <button class="aim-btn aim-btn-dl" id="aim-dl-btn">⬇ DOWNLOAD</button>
        </div>
      </div>
    </div>
  `;

  // Toggle collapsibility
  el.querySelector('#aim-result-toggle').onclick = () => {
    const area = el.querySelector('#aim-result-content-area');
    const icon = el.querySelector('#aim-result-toggle-icon');
    if (area.style.display === 'none') {
      area.style.display = 'block';
      icon.textContent = '▼';
    } else {
      area.style.display = 'none';
      icon.textContent = '▶';
    }
  };

  if (urls.length > 1) {
    const imgEl = el.querySelector('#aim-result-img');
    const countEl = el.querySelector('.aim-batch-count');
    const actionsRow = el.querySelector('.aim-result-actions');
    
    // Create thumbnails container
    const thumbContainer = document.createElement('div');
    thumbContainer.className = 'aim-result-thumbnails';
    thumbContainer.style.display = 'flex';
    thumbContainer.style.gap = '8px';
    thumbContainer.style.marginTop = '10px';
    thumbContainer.style.overflowX = 'auto';
    thumbContainer.style.padding = '4px 0';

    let slideshowTimer = null;
    const slideshowBtn = el.querySelector('#aim-slideshow-btn');

    function stopSlideshow() {
      if (slideshowTimer) {
        clearInterval(slideshowTimer);
        slideshowTimer = null;
      }
      if (slideshowBtn) {
        slideshowBtn.innerHTML = '▶ AUTO';
        slideshowBtn.style.background = '';
      }
    }

    function advanceSlide() {
      currentIdx = (currentIdx + 1) % urls.length;
      imgEl.src = urls[currentIdx];
      countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
      Array.from(thumbContainer.children).forEach((t, i) => {
        t.style.border = i === currentIdx ? '2px solid var(--accent)' : '2px solid transparent';
      });
    }

    if (slideshowBtn) {
      slideshowBtn.onclick = () => {
        if (slideshowTimer) {
          stopSlideshow();
        } else {
          slideshowBtn.innerHTML = '⏸ PAUSE';
          slideshowBtn.style.background = 'rgba(6, 182, 212, 0.3)';
          slideshowTimer = setInterval(advanceSlide, 2200);
        }
      };
    }
    
    // Add thumbnails
    urls.forEach((u, idx) => {
      const thumb = document.createElement('img');
      thumb.src = u;
      thumb.style.width = '60px';
      thumb.style.height = '60px';
      thumb.style.objectFit = 'cover';
      thumb.style.cursor = 'pointer';
      thumb.style.borderRadius = '4px';
      thumb.style.border = idx === 0 ? '2px solid var(--accent)' : '2px solid transparent';
      thumb.style.transition = 'border 0.2s';
      
      thumb.onclick = () => {
        stopSlideshow();
        currentIdx = idx;
        imgEl.src = urls[currentIdx];
        countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
        Array.from(thumbContainer.children).forEach((t, i) => {
          t.style.border = i === currentIdx ? '2px solid var(--accent)' : '2px solid transparent';
        });
      };
      thumbContainer.appendChild(thumb);
    });
    
    // Insert thumbnails before actions row
    actionsRow.parentNode.insertBefore(thumbContainer, actionsRow);
    
    // Keep next/prev buttons but update thumbnails highlighting
    el.querySelector('#aim-prev-btn').onclick = () => {
      stopSlideshow();
      currentIdx = (currentIdx - 1 + urls.length) % urls.length;
      imgEl.src = urls[currentIdx];
      countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
      Array.from(thumbContainer.children).forEach((t, i) => t.style.border = i === currentIdx ? '2px solid var(--accent)' : '2px solid transparent');
    };
    
    el.querySelector('#aim-next-btn').onclick = () => {
      stopSlideshow();
      currentIdx = (currentIdx + 1) % urls.length;
      imgEl.src = urls[currentIdx];
      countEl.textContent = `${currentIdx + 1} / ${urls.length}`;
      Array.from(thumbContainer.children).forEach((t, i) => t.style.border = i === currentIdx ? '2px solid var(--accent)' : '2px solid transparent');
    };

    el.querySelector('#aim-dl-all-btn').onclick = () => {
      urls.forEach((u, idx) => {
        const a = document.createElement('a');
        a.href = u;
        a.download = `alphacore_output_${Date.now()}_${idx}.png`;
        setTimeout(() => a.click(), idx * 200); // Stagger downloads
      });
    };
  }

  el.querySelector('#aim-dl-btn').onclick = () => {
    const a = document.createElement('a');
    a.href = urls[currentIdx];
    a.download = `alphacore_output_${Date.now()}_${currentIdx}.png`;
    a.click();
  };

  return el;
}

/* ─── TXT2IMG PANEL ─────────────────────────────────────────── */
function buildTxt2Img() {
  const settings = getModalSettings();
  const currentProfile = (sessionStorage.getItem('current_profile') || 'Guest').toLowerCase();
  const isArchitect = currentProfile === 'archetect' || currentProfile === 'architect' || currentProfile === 'creator' || sessionStorage.getItem('admin_authenticated') === '1';
  const maxBatchCount = isArchitect ? 20 : 5;

  const wrap = document.createElement('div');
  wrap.className = 'aim-panel';
  wrap.innerHTML = `
    <div class="aim-panel-header">
      <span class="aim-panel-icon">✦</span>
      <span class="aim-panel-title">TEXT TO IMAGE</span>
      <span class="aim-panel-badge">SDXL ENGINE</span>
    </div>

    <div class="aim-field">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:6px;">
        <label class="aim-label" for="t2i-prompt" style="margin:0;">PROMPT MATRIX</label>
        <button class="aim-btn aim-btn-sm" id="t2i-enhance-btn" style="padding:2px 10px; font-size:0.75rem; background:rgba(6,182,212,0.15); border-color:var(--accent); color:var(--accent);" title="Auto-enhance prompt with AI matrix descriptors">✨ AI ENHANCE</button>
      </div>
      <textarea class="aim-textarea" id="t2i-prompt" rows="4" placeholder="Describe what you want to generate..."></textarea>
    </div>

    ${(() => {
      const injected = localStorage.getItem('alphacore_injected_prompt');
      if (injected) {
        localStorage.removeItem('alphacore_injected_prompt');
        setTimeout(() => {
          const pInput = wrap.querySelector('#t2i-prompt');
          if (pInput) pInput.value = injected;
        }, 50);
      }
      return '';
    })()}

    <div class="aim-row">
      <div class="aim-field aim-field-half">
        <label class="aim-label">SPEED MODE</label>
        <div class="aim-seg aim-seg-3" id="t2i-speed">
          <button class="aim-seg-btn active" data-steps="${settings.stepsFastTxt}">⚡ FAST</button>
          <button class="aim-seg-btn" data-steps="${settings.stepsNormalTxt}">⚖ NORMAL</button>
          <button class="aim-seg-btn" data-steps="${settings.stepsFocusedTxt}">🎯 FOCUSED</button>
        </div>
      </div>
      <div class="aim-field aim-field-half">
        <label class="aim-label" for="t2i-model-select">BASE MODEL</label>
        <select class="aim-input" id="t2i-model-select">
          <option value="juggernautXL_ragnarok.safetensors">JUGGERNAUT RAGNAROK</option>
          <option value="cyberrealistic_final.safetensors">CYBERREALISTIC FINAL</option>
          <option value="unholyDesireMixFoolS_v60.safetensors">UNHOLY DESIRE MIX</option>
          <option value="autismmixSDXL_autismmixPony.safetensors">AUTISMMIX PONY</option>
          <option value="lustifyNSFWCheckpoint_zenithV9.safetensors">LUSTIFY ZENITH V9</option>
          <option value="epicrealismXL_pureFix.safetensors">EPICREALISM</option>
        </select>
      </div>
    </div>

    <div class="aim-row">
      <div class="aim-field aim-field-half">
        <label class="aim-label" for="t2i-batch">BATCH COUNT (1-${maxBatchCount}) ${isArchitect ? '<span style="color:#10b981; margin-left:4px;">[UNLIMITED]</span>' : '<span style="color:#f59e0b; margin-left:4px;">[MAX 5]</span>'}</label>
        <input class="aim-input" type="number" id="t2i-batch" min="1" max="${maxBatchCount}" value="1" />
      </div>
        <div class="aim-field" id="t2i-lora-field" style="display: ${sessionStorage.getItem('lora_authenticated') ? 'block' : 'none'};">
          <label class="aim-label" for="t2i-lora">ACTIVE LORAS (CTRL+CLICK) ${sessionStorage.getItem('darkness_mode_active') !== 'true' ? '<span style="color:#ff003c; margin-left:4px;">[LOCKED]</span>' : ''}</label>
          <select class="aim-input aim-lora-select" id="t2i-lora" multiple ${sessionStorage.getItem('darkness_mode_active') === 'true' ? '' : 'disabled'}>
            ${LORA_OPTIONS}
          </select>
        </div>
    </div>

    <details class="aim-advanced">
      <summary class="aim-advanced-toggle">▶ ADVANCED PARAMETERS & HYPERPARAMETERS</summary>
      <div class="aim-advanced-body">
        <div class="aim-field">
          <label class="aim-label" for="t2i-neg">NEGATIVE PROMPT</label>
          <textarea class="aim-textarea aim-textarea-sm" id="t2i-neg" rows="2">${settings.negativePrompt}</textarea>
        </div>
        
        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-cfg">GUIDANCE SCALE (CFG): <span class="aim-val-display" id="t2i-cfg-val">${parseFloat(settings.guidanceScale).toFixed(1)}</span></label>
            <input class="aim-range" type="range" id="t2i-cfg" min="1" max="20" step="0.5" value="${settings.guidanceScale}" />
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-denoise">DENOISING STRENGTH: <span class="aim-val-display" id="t2i-denoise-val">0.75</span></label>
            <input class="aim-range" type="range" id="t2i-denoise" min="0.05" max="1.00" step="0.05" value="0.75" />
          </div>
        </div>

        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-scheduler">SAMPLER / SCHEDULER</label>
            <select class="aim-input" id="t2i-scheduler">
              <option value="Euler a" selected>Euler Ancestral (Euler a)</option>
              <option value="Euler">Euler</option>
              <option value="DPM++ 2M">DPM++ 2M</option>
              <option value="DPM++ 2M Karras">DPM++ 2M Karras</option>
              <option value="DPM++ SDE Karras">DPM++ SDE Karras</option>
              <option value="DDIM">DDIM</option>
              <option value="UniPC">UniPC</option>
              <option value="Heun">Heun</option>
            </select>
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-clip-skip">CLIP SKIP</label>
            <select class="aim-input" id="t2i-clip-skip">
              <option value="1" selected>Clip Skip 1 (Standard)</option>
              <option value="2">Clip Skip 2 (Anime/SDXL)</option>
            </select>
          </div>
        </div>

        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-seed">SEED (-1 FOR RANDOM)</label>
            <input class="aim-input" type="number" id="t2i-seed" value="-1" placeholder="-1" />
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="t2i-aspect">ASPECT RATIO</label>
            <select class="aim-input" id="t2i-aspect">
              <option value="1024x1024" selected>1:1 Square (1024x1024)</option>
              <option value="832x1216">2:3 Portrait (832x1216)</option>
              <option value="1216x832">3:2 Landscape (1216x832)</option>
              <option value="1024x1536">9:16 Mobile Tall (1024x1536)</option>
              <option value="1536x1024">16:9 Widescreen (1536x1024)</option>
            </select>
          </div>
        </div>
      </div>
    </details>

      <button class="aim-btn-generate" id="t2i-gen-btn" style="${!sessionStorage.getItem('generate_authenticated') ? 'background:rgba(255,0,60,0.15); border-color:#ff003c; color:#ff003c;' : ''}">
        <span class="aim-btn-icon">${sessionStorage.getItem('generate_authenticated') ? '⚡' : '🔒'}</span> ${sessionStorage.getItem('generate_authenticated') ? 'INITIALIZE SYNTHESIS' : 'GUEST PREVIEW MODE — CLICK TO LOGIN'}
      </button>

    <div class="aim-status-bar" id="t2i-status"></div>
    <div id="t2i-loader-slot"></div>
    <div id="t2i-result-slot"></div>
  `;

  // AI Prompt Enhance listener
  wrap.querySelector('#t2i-enhance-btn').addEventListener('click', () => {
    const promptInput = wrap.querySelector('#t2i-prompt');
    const enhanced = enhancePromptWithAI(promptInput.value);
    if (enhanced) {
      promptInput.value = enhanced;
      setStatus(wrap, '#t2i-status', 'PROMPT MATRIX ENHANCED WITH AI DESCRIPTORS.', 'ok');
    }
  });

  // Wire up segment controls
  wrap.querySelectorAll('#t2i-speed .aim-seg-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      wrap.querySelectorAll('#t2i-speed .aim-seg-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });

  // Range displays
  const cfgInput = wrap.querySelector('#t2i-cfg');
  const cfgVal = wrap.querySelector('#t2i-cfg-val');
  if (cfgInput && cfgVal) cfgInput.addEventListener('input', () => { cfgVal.textContent = parseFloat(cfgInput.value).toFixed(1); });

  const denoiseInput = wrap.querySelector('#t2i-denoise');
  const denoiseVal = wrap.querySelector('#t2i-denoise-val');
  if (denoiseInput && denoiseVal) denoiseInput.addEventListener('input', () => { denoiseVal.textContent = parseFloat(denoiseInput.value).toFixed(2); });

  // Generate
  wrap.querySelector('#t2i-gen-btn').addEventListener('click', async () => {
    if (!sessionStorage.getItem('generate_authenticated')) {
      setStatus(wrap, '#t2i-status', 'GUEST PREVIEW MODE: Please log in with a profile PIN to execute image generation.', 'error');
      import('../components/pinpad.js').then(({ openLoginModal }) => {
        openLoginModal({ title: '// LOGIN REQUIRED', subtitle: 'ENTER ACCESS PIN TO GENERATE IMAGES' });
      });
      return;
    }
    const prompt = wrap.querySelector('#t2i-prompt').value.trim();
    if (!prompt) { setStatus(wrap, '#t2i-status', 'ERROR: Prompt matrix is empty.', 'error'); return; }

    const steps = parseInt(wrap.querySelector('#t2i-speed .aim-seg-btn.active').dataset.steps);
    const modelStr = wrap.querySelector('#t2i-model-select').value;
    let neg = wrap.querySelector('#t2i-neg').value;
    const cfg = parseFloat(wrap.querySelector('#t2i-cfg').value).toFixed(1);
    const denoise = parseFloat(wrap.querySelector('#t2i-denoise')?.value || '0.75');
    const scheduler = wrap.querySelector('#t2i-scheduler')?.value || 'Euler a';
    const clipSkip = wrap.querySelector('#t2i-clip-skip')?.value || '1';
    const seed = parseInt(wrap.querySelector('#t2i-seed')?.value || '-1');
    const aspect = wrap.querySelector('#t2i-aspect')?.value || '1024x1024';
    const [w, h] = aspect.split('x').map(n => parseInt(n));

    const batchSize = parseInt(wrap.querySelector('#t2i-batch').value) || 1;
    if (batchSize > maxBatchCount) {
      setStatus(wrap, '#t2i-status', `ERROR: Max batch count allowed for profile '${currentProfile}' is ${maxBatchCount}. Login as 'archetect' for unlimited batching.`, 'error');
      return;
    }

    const loraSelect = wrap.querySelector('#t2i-lora');
    let lora = '';
    if (loraSelect && !loraSelect.disabled) {
      lora = Array.from(loraSelect.selectedOptions).map(opt => opt.value).join(',');
    }

    // Check for darkness mode and override negative prompt
    if (sessionStorage.getItem('darkness_mode_active') === 'true') {
      neg = ''; // Override negative prompt, removing restrictions.
      console.warn('[DARKNESS] NSFW governors disabled for this T2I request.');
    }

    const loaderSlot = wrap.querySelector('#t2i-loader-slot');
    const resultSlot = wrap.querySelector('#t2i-result-slot');
    const genBtn = wrap.querySelector('#t2i-gen-btn');

    genBtn.disabled = true;
    setStatus(wrap, '#t2i-status', 'ROUTING TO GPU NODE...', 'info');
    const loader = buildLoader('SYNTHESIZING IMAGE...');
    loaderSlot.innerHTML = '';
    loaderSlot.appendChild(loader);

    const loaderMessages = ['SYNTHESIZING IMAGE...','DENOISING LATENTS...','RENDERING ARTIFACT...','FINALIZING OUTPUT...'];
    let msgIdx = 0;
    const msgInterval = setInterval(() => {
      msgIdx = (msgIdx + 1) % loaderMessages.length;
      const ltEl = loaderSlot.querySelector('#aim-loader-text');
      if (ltEl) ltEl.textContent = loaderMessages[msgIdx];
    }, 2500);

    try {
      // Derive backwards-compatible flags for legacy modal endpoints if needed
      let juggFlag = '0';
      let cyberFlag = '0';
      if (modelStr.includes('juggernaut')) { juggFlag = '1'; }
      if (modelStr.includes('cyberrealistic')) { cyberFlag = '1'; }
      if (modelStr.includes('unholy')) { juggFlag = '1'; cyberFlag = '1'; }

      const params = new URLSearchParams({
        prompt,
        model: modelStr,
        checkpoint: modelStr,
        model_name: modelStr,
        checkpoint_name: modelStr,
        base_model: modelStr,
        selected_model: modelStr,
        JuggernautXL: juggFlag,
        CyberRealisticXL: cyberFlag,
        negative_prompt: neg,
        guidance_scale: cfg,
        num_inference_steps: steps,
        batch_size: batchSize,
        lora: lora,
        scheduler: scheduler,
        sampler: scheduler,
        denoising_strength: denoise,
        strength: denoise,
        seed: seed,
        clip_skip: clipSkip,
        width: w,
        height: h,
      });
      const res = await fetch(`${settings.txt2imgUrl}stream?${params}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let url = null;

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        const lines = buffer.split('\n\n');
        buffer = lines.pop(); 

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const dataStr = line.substring(6);
            try {
              const data = JSON.parse(dataStr);
              if (data.step !== undefined && data.max_steps !== undefined) {
                updateProgress(loader, data.step, data.max_steps);
              } else if (data.image_b64) {
                const b64s = Array.isArray(data.image_b64) ? data.image_b64 : [data.image_b64];
                const profile = sessionStorage.getItem('current_profile') || 'UNKNOWN';
                b64s.forEach(b64 => {
                   saveImageToGallery(profile, prompt, 'Straight Image Gen (T2I)', 'data:image/png;base64,' + b64);
                });
                url = b64s.map(b64 => {
                  const byteCharacters = atob(b64);
                  const byteNumbers = new Array(byteCharacters.length);
                  for (let i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                  }
                  const byteArray = new Uint8Array(byteNumbers);
                  const blob = new Blob([byteArray], {type: 'image/png'});
                  return URL.createObjectURL(blob);
                });
              } else if (data.error) {
                throw new Error(data.error);
              }
            } catch (e) {
              if (e.message !== "Unexpected end of JSON input" && !e.message.includes('JSON')) {
                throw e; 
              }
            }
          }
        }
      }

      if (!url || url.length === 0) throw new Error("Stream finished but no image received");

      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';

      const resultEl = buildResult(url);
      resultEl.classList.remove('hidden');
      resultSlot.innerHTML = '';
      resultSlot.appendChild(resultEl);
      setStatus(wrap, '#t2i-status', 'ARTIFACT RENDERED SUCCESSFULLY.', 'ok');
      logAction('IMAGE_GENERATED', { type: 'T2I', prompt, batchSize });
      if (window._aimNotifyWarm) window._aimNotifyWarm();
    } catch (err) {
      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';
      setStatus(wrap, '#t2i-status', `FAILURE: ${err.message}`, 'error');
    } finally {
      genBtn.disabled = false;
    }
  });

  return wrap;
}

/* ─── IMG2IMG PANEL ─────────────────────────────────────────── */
function buildImg2Img() {
  const settings = getModalSettings();
  const currentProfile = (sessionStorage.getItem('current_profile') || 'Guest').toLowerCase();
  const isArchitect = currentProfile === 'archetect' || currentProfile === 'architect' || currentProfile === 'creator' || sessionStorage.getItem('admin_authenticated') === '1';
  const maxBatchCount = isArchitect ? 20 : 5;

  const wrap = document.createElement('div');
  wrap.className = 'aim-panel';
  wrap.innerHTML = `
    <div class="aim-panel-header">
      <span class="aim-panel-icon">🎨</span>
      <span class="aim-panel-title">IMAGE TO IMAGE EDITING</span>
      <span class="aim-panel-badge">QWEN EDIT PLUS</span>
    </div>

    <div class="aim-row" style="display:flex; gap:10px;">
      <div class="aim-field" style="flex:1;">
        <label class="aim-label">PRIMARY IMAGE</label>
        <div class="aim-dropzone" id="i2i-dropzone">
          <input type="file" id="i2i-file" accept="image/*" class="aim-file-input" />
          <div class="aim-dropzone-inner" id="i2i-dz-inner">
            <div class="aim-dz-icon">📁</div>
            <div class="aim-dz-text">DROP IMAGE</div>
          </div>
          <img class="aim-dz-preview hidden" id="i2i-preview" alt="preview" />
        </div>
      </div>
      <div class="aim-field" style="flex:1;">
        <label class="aim-label">SECONDARY IMAGE (OPTIONAL)</label>
        <div class="aim-dropzone" id="i2i-dropzone2">
          <input type="file" id="i2i-file2" accept="image/*" class="aim-file-input" />
          <div class="aim-dropzone-inner" id="i2i-dz-inner2">
            <div class="aim-dz-icon">📁</div>
            <div class="aim-dz-text">DROP IMAGE</div>
          </div>
          <img class="aim-dz-preview hidden" id="i2i-preview2" alt="preview" />
        </div>
      </div>
    </div>

    <div class="aim-field">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:6px;">
        <label class="aim-label" for="i2i-prompt" style="margin:0;">EDIT INSTRUCTION</label>
        <button class="aim-btn aim-btn-sm" id="i2i-enhance-btn" style="padding:2px 10px; font-size:0.75rem; background:rgba(6,182,212,0.15); border-color:var(--accent); color:var(--accent);" title="Auto-enhance instruction with AI matrix descriptors">✨ AI ENHANCE</button>
      </div>
      <textarea class="aim-textarea" id="i2i-prompt" rows="3" placeholder="Describe the edits you want applied to the image..."></textarea>
    </div>

    <div class="aim-field">
      <label class="aim-label">PROCESSING MODE</label>
      <div class="aim-seg aim-seg-3" id="i2i-speed">
        <button class="aim-seg-btn active" data-steps="${settings.stepsFastImg}">⚡ FAST</button>
        <button class="aim-seg-btn" data-steps="${settings.stepsNormalImg}">⚖ NORMAL</button>
        <button class="aim-seg-btn" data-steps="${settings.stepsFocusedImg}">🎯 FOCUSED</button>
      </div>
    </div>

    <div class="aim-row">
      <div class="aim-field" style="width: 100%;">
        <label class="aim-label" for="i2i-batch">BATCH COUNT (1-${maxBatchCount}) ${isArchitect ? '<span style="color:#10b981; margin-left:4px;">[UNLIMITED]</span>' : '<span style="color:#f59e0b; margin-left:4px;">[MAX 5]</span>'}</label>
        <input class="aim-input" type="number" id="i2i-batch" min="1" max="${maxBatchCount}" value="1" />
      </div>
    </div>

    <details class="aim-advanced">
      <summary class="aim-advanced-toggle">▶ ADVANCED PARAMETERS & HYPERPARAMETERS</summary>
      <div class="aim-advanced-body">
        <div class="aim-field">
          <label class="aim-label" for="i2i-neg">NEGATIVE PROMPT</label>
          <textarea class="aim-textarea aim-textarea-sm" id="i2i-neg" rows="2">${settings.negativePrompt}</textarea>
        </div>
        
        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-cfg">GUIDANCE SCALE (CFG): <span class="aim-val-display" id="i2i-cfg-val">${parseFloat(settings.guidanceImg).toFixed(1)}</span></label>
            <input class="aim-range" type="range" id="i2i-cfg" min="1" max="20" step="0.5" value="${settings.guidanceImg}" />
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-denoise">DENOISING STRENGTH: <span class="aim-val-display" id="i2i-denoise-val">0.75</span></label>
            <input class="aim-range" type="range" id="i2i-denoise" min="0.05" max="1.00" step="0.05" value="0.75" />
          </div>
        </div>

        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-scheduler">SAMPLER / SCHEDULER</label>
            <select class="aim-input" id="i2i-scheduler">
              <option value="Euler a" selected>Euler Ancestral (Euler a)</option>
              <option value="Euler">Euler</option>
              <option value="DPM++ 2M">DPM++ 2M</option>
              <option value="DPM++ 2M Karras">DPM++ 2M Karras</option>
              <option value="DPM++ SDE Karras">DPM++ SDE Karras</option>
              <option value="DDIM">DDIM</option>
              <option value="UniPC">UniPC</option>
              <option value="Heun">Heun</option>
            </select>
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-clip-skip">CLIP SKIP</label>
            <select class="aim-input" id="i2i-clip-skip">
              <option value="1" selected>Clip Skip 1 (Standard)</option>
              <option value="2">Clip Skip 2 (Anime/SDXL)</option>
            </select>
          </div>
        </div>

        <div class="aim-row" style="margin-top:12px;">
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-seed">SEED (-1 FOR RANDOM)</label>
            <input class="aim-input" type="number" id="i2i-seed" value="-1" placeholder="-1" />
          </div>
          <div class="aim-field aim-field-half">
            <label class="aim-label" for="i2i-aspect">ASPECT RATIO</label>
            <select class="aim-input" id="i2i-aspect">
              <option value="1024x1024" selected>1:1 Square (1024x1024)</option>
              <option value="832x1216">2:3 Portrait (832x1216)</option>
              <option value="1216x832">3:2 Landscape (1216x832)</option>
              <option value="1024x1536">9:16 Mobile Tall (1024x1536)</option>
              <option value="1536x1024">16:9 Widescreen (1536x1024)</option>
            </select>
          </div>
        </div>
      </div>
    </details>

    <button class="aim-btn aim-btn-generate" id="i2i-gen-btn" style="${!sessionStorage.getItem('generate_authenticated') ? 'background:rgba(255,0,60,0.15); border-color:#ff003c; color:#ff003c;' : ''}">
      <span class="aim-btn-icon">${sessionStorage.getItem('generate_authenticated') ? '⚡' : '🔒'}</span> ${sessionStorage.getItem('generate_authenticated') ? 'INITIATE EDIT' : 'GUEST PREVIEW MODE — CLICK TO LOGIN'}
    </button>

    <div class="aim-status-bar" id="i2i-status"></div>
    <div id="i2i-loader-slot"></div>
    <div id="i2i-result-slot"></div>
  `;

  // AI Prompt Enhance listener
  wrap.querySelector('#i2i-enhance-btn').addEventListener('click', () => {
    const promptInput = wrap.querySelector('#i2i-prompt');
    const enhanced = enhancePromptWithAI(promptInput.value);
    if (enhanced) {
      promptInput.value = enhanced;
      setStatus(wrap, '#i2i-status', 'EDIT INSTRUCTION ENHANCED WITH AI DESCRIPTORS.', 'ok');
    }
  });

  // Speed selector
  wrap.querySelectorAll('#i2i-speed .aim-seg-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      wrap.querySelectorAll('#i2i-speed .aim-seg-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    });
  });

  // Range displays
  const i2iCfgInput = wrap.querySelector('#i2i-cfg');
  const i2iCfgVal = wrap.querySelector('#i2i-cfg-val');
  if (i2iCfgInput && i2iCfgVal) {
    i2iCfgInput.addEventListener('input', () => {
      i2iCfgVal.textContent = parseFloat(i2iCfgInput.value).toFixed(1);
    });
  }

  const i2iDenoiseInput = wrap.querySelector('#i2i-denoise');
  const i2iDenoiseVal = wrap.querySelector('#i2i-denoise-val');
  if (i2iDenoiseInput && i2iDenoiseVal) {
    i2iDenoiseInput.addEventListener('input', () => {
      i2iDenoiseVal.textContent = parseFloat(i2iDenoiseInput.value).toFixed(2);
    });
  }

  const fileInput = wrap.querySelector('#i2i-file');
  const dropzone = wrap.querySelector('#i2i-dropzone');
  const dzInner = wrap.querySelector('#i2i-dz-inner');
  const preview = wrap.querySelector('#i2i-preview');

  const fileInput2 = wrap.querySelector('#i2i-file2');
  const dropzone2 = wrap.querySelector('#i2i-dropzone2');
  const dzInner2 = wrap.querySelector('#i2i-dz-inner2');
  const preview2 = wrap.querySelector('#i2i-preview2');

  function showPreview(file, prv, dzI, dz) {
    if (!file) return;
    const url = URL.createObjectURL(file);
    prv.src = url;
    prv.classList.remove('hidden');
    dzI.classList.add('hidden');
    dz.classList.add('has-preview');
  }

  function bindDropzone(fInput, dz, dzI, prv) {
    fInput.addEventListener('change', () => { if (fInput.files[0]) showPreview(fInput.files[0], prv, dzI, dz); });
    dz.addEventListener('click', e => {
      if (e.target === fInput || e.target.classList.contains('aim-dz-preview')) return;
      fInput.click();
    });
    dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('drag-over'); });
    dz.addEventListener('dragleave', () => dz.classList.remove('drag-over'));
    dz.addEventListener('drop', e => {
      e.preventDefault();
      dz.classList.remove('drag-over');
      const file = e.dataTransfer.files[0];
      if (file && file.type.startsWith('image/')) { fInput._droppedFile = file; showPreview(file, prv, dzI, dz); }
    });
  }

  bindDropzone(fileInput, dropzone, dzInner, preview);
  bindDropzone(fileInput2, dropzone2, dzInner2, preview2);

  // Generate
  wrap.querySelector('#i2i-gen-btn').addEventListener('click', async () => {
    if (!sessionStorage.getItem('generate_authenticated')) {
      setStatus(wrap, '#i2i-status', 'GUEST PREVIEW MODE: Please log in with a profile PIN to execute image editing.', 'error');
      import('../components/pinpad.js').then(({ openLoginModal }) => {
        openLoginModal({ title: '// LOGIN REQUIRED', subtitle: 'ENTER ACCESS PIN TO EDIT IMAGES' });
      });
      return;
    }
    const file = fileInput._droppedFile || fileInput.files[0];
    const file2 = fileInput2._droppedFile || fileInput2.files[0];
    if (!file) { setStatus(wrap, '#i2i-status', 'ERROR: No primary image loaded.', 'error'); return; }
    const prompt = wrap.querySelector('#i2i-prompt').value.trim();
    if (!prompt) { setStatus(wrap, '#i2i-status', 'ERROR: Edit instruction is empty.', 'error'); return; }

    const steps = parseInt(wrap.querySelector('#i2i-speed .aim-seg-btn.active').dataset.steps);
    let neg = wrap.querySelector('#i2i-neg').value;
    const cfg = parseFloat(wrap.querySelector('#i2i-cfg').value).toFixed(1);
    const denoise = parseFloat(wrap.querySelector('#i2i-denoise')?.value || '0.75');
    const scheduler = wrap.querySelector('#i2i-scheduler')?.value || 'Euler a';
    const clipSkip = wrap.querySelector('#i2i-clip-skip')?.value || '1';
    const seed = parseInt(wrap.querySelector('#i2i-seed')?.value || '-1');
    const aspect = wrap.querySelector('#i2i-aspect')?.value || '1024x1024';
    const [w, h] = aspect.split('x').map(n => parseInt(n));

    const batchSize = parseInt(wrap.querySelector('#i2i-batch').value) || 1;
    if (batchSize > maxBatchCount) {
      setStatus(wrap, '#i2i-status', `ERROR: Max batch count allowed for profile '${currentProfile}' is ${maxBatchCount}. Login as 'archetect' for unlimited batching.`, 'error');
      return;
    }

    // Check for darkness mode and override negative prompt
    if (sessionStorage.getItem('darkness_mode_active') === 'true') {
      neg = ''; // Override negative prompt, removing restrictions.
      console.warn('[DARKNESS] NSFW governors disabled for this I2I request.');
    }

    const loaderSlot = wrap.querySelector('#i2i-loader-slot');
    const resultSlot = wrap.querySelector('#i2i-result-slot');
    const genBtn = wrap.querySelector('#i2i-gen-btn');

    genBtn.disabled = true;
    setStatus(wrap, '#i2i-status', 'ROUTING TO GPU NODE...', 'info');
    const loader = buildLoader('PROCESSING EDIT...');
    loaderSlot.innerHTML = '';
    loaderSlot.appendChild(loader);

    const loaderMessages = ['PROCESSING EDIT...','APPLYING INSTRUCTION...','DIFFUSING CHANGES...','RENDERING OUTPUT...'];
    let msgIdx = 0;
    const msgInterval = setInterval(() => {
      msgIdx = (msgIdx + 1) % loaderMessages.length;
      const ltEl = loaderSlot.querySelector('#aim-loader-text');
      if (ltEl) ltEl.textContent = loaderMessages[msgIdx];
    }, 2500);

    try {
      const formData = new FormData();
      formData.append('image', file);
      if (file2) formData.append('image2', file2);
      formData.append('prompt', prompt);
      formData.append('negative_prompt', neg);
      formData.append('num_inference_steps', steps);
      formData.append('true_cfg_scale', cfg);
      formData.append('batch_size', batchSize);
      formData.append('lora', lora);
      formData.append('scheduler', scheduler);
      formData.append('sampler', scheduler);
      formData.append('denoising_strength', denoise);
      formData.append('strength', denoise);
      formData.append('seed', seed);
      formData.append('clip_skip', clipSkip);
      formData.append('width', w);
      formData.append('height', h);

      const res = await fetch(`${settings.img2imgUrl}stream`, { method: 'POST', body: formData });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let url = null;

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        const lines = buffer.split('\n\n');
        buffer = lines.pop(); 

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const dataStr = line.substring(6);
            try {
              const data = JSON.parse(dataStr);
              if (data.step !== undefined && data.max_steps !== undefined) {
                updateProgress(loader, data.step, data.max_steps);
              } else if (data.image_b64) {
                const b64s = Array.isArray(data.image_b64) ? data.image_b64 : [data.image_b64];
                const profile = sessionStorage.getItem('current_profile') || 'UNKNOWN';
                b64s.forEach(b64 => {
                   saveImageToGallery(profile, prompt, 'Straight Image Gen (I2I)', 'data:image/png;base64,' + b64);
                });
                url = b64s.map(b64 => {
                  const byteCharacters = atob(b64);
                  const byteNumbers = new Array(byteCharacters.length);
                  for (let i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                  }
                  const byteArray = new Uint8Array(byteNumbers);
                  const blob = new Blob([byteArray], {type: 'image/png'});
                  return URL.createObjectURL(blob);
                });
              } else if (data.error) {
                throw new Error(data.error);
              }
            } catch (e) {
              if (e.message !== "Unexpected end of JSON input" && !e.message.includes('JSON')) {
                throw e; 
              }
            }
          }
        }
      }

      if (!url || url.length === 0) throw new Error("Stream finished but no image received");

      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';

      const resultEl = buildResult(url);
      resultEl.classList.remove('hidden');
      resultSlot.innerHTML = '';
      resultSlot.appendChild(resultEl);
      setStatus(wrap, '#i2i-status', 'EDIT APPLIED SUCCESSFULLY.', 'ok');
      logAction('IMAGE_GENERATED', { type: 'I2I', prompt, batchSize });
      if (window._aimNotifyWarm) window._aimNotifyWarm();
    } catch (err) {
      clearInterval(msgInterval);
      loaderSlot.innerHTML = '';
      setStatus(wrap, '#i2i-status', `FAILURE: ${err.message}`, 'error');
    } finally {
      genBtn.disabled = false;
    }
  });

  return wrap;
}

/* ─── HELPERS ────────────────────────────────────────────────── */
function setStatus(root, sel, msg, type = '') {
  const el = root.querySelector(sel);
  if (!el) return;
  el.textContent = `> ${msg}`;
  el.className = 'aim-status-bar' + (type ? ` aim-status-${type}` : '');
}

/* ─── MAIN PAGE ─────────────────────────────────────────────── */
export default function AiModals() {
  const container = createElement('div', { class: 'aimodals-page' });

  function showNextStep() {
    container.innerHTML = '';
    // If disclaimer not accepted this session, show it first
    if (!sessionStorage.getItem('aim_disclaimer_accepted')) {
      container.appendChild(buildDisclaimer(() => {
        container.innerHTML = '';
        container.appendChild(buildMainUI());
      }));
    } else {
      container.appendChild(buildMainUI());
    }
  }

  requireAuth(container, {
    authKey: 'aimodals_authenticated',
    requiredRole: 'aimodals',
    onSuccess: showNextStep,
    title: '// SECURITY_LOCKOUT',
    subtitle: 'UNRESTRICTED GENERATION ACCESS',
    icon: '🔒'
  });

  return container;
}


function buildMainUI() {
  const root = document.createElement('div');
  root.className = 'aim-root';
  root.innerHTML = `
    <div class="aim-header">
      <div class="aim-header-badge">[SYS_MODULE] // GENERATIVE_AI</div>
      <h1 class="glitch aim-title" data-text="AI MODALS // SYNTHESIS_ENGINE">AI MODALS // SYNTHESIS_ENGINE</h1>
      <div class="header-line"></div>
      <p class="aim-subtitle">Neural image synthesis via Modal GPU infrastructure. Select a generation mode below.</p>
      
      <div class="aim-status-panel" style="margin-top: 15px; padding: 10px; border: 1px solid var(--accent); background: rgba(255,0,60,0.05); display: flex; align-items: center; gap: 15px; flex-wrap: wrap;">
        <div id="aim-backend-status" style="font-weight: bold; flex: 1; color: #00ffff; font-family: 'Courier New', monospace;">STATUS: ❄ COLD BOOT</div>
        <button id="aim-lock-btn" class="aim-btn aim-btn-sm" style="font-size: 0.8rem; padding: 6px 12px;">🔒 LOCK ON (15M)</button>
        <button id="aim-shutdown-btn" class="aim-btn aim-btn-sm aim-btn-decline" style="font-size: 0.8rem; padding: 6px 12px; margin-top: 0;">⏻ SHUT DOWN</button>
      </div>
    </div>

    <div class="aim-tabs" id="aim-tabs">
      <button class="aim-tab active" data-tab="txt2img" id="aim-tab-t2i">
        <span class="aim-tab-icon">✦</span> TXT2IMG
      </button>
      <button class="aim-tab" data-tab="img2img" id="aim-tab-i2i">
        <span class="aim-tab-icon">⟁</span> IMG2IMG
      </button>
      <button class="aim-tab" data-tab="framepack" id="aim-tab-fp">
        <span class="aim-tab-icon">🎬</span> FRAMEPACK
      </button>
    </div>

    <div id="aim-content"></div>
  `;

  const content = root.querySelector('#aim-content');
  const tabs = root.querySelectorAll('.aim-tab');

  let currentPanel = buildTxt2Img();
  content.appendChild(currentPanel);

  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => t.classList.remove('active'));
      tab.classList.add('active');
      content.innerHTML = '';
      if (tab.dataset.tab === 'txt2img') {
        currentPanel = buildTxt2Img();
      } else if (tab.dataset.tab === 'img2img') {
        currentPanel = buildImg2Img();
      } else {
        currentPanel = buildFramepack();
      }
      content.appendChild(currentPanel);
    });
  });

  // --- Backend Status Logic ---
  const settings = getModalSettings();
  let lockInterval = null;
  let expireTime = 0;
  let displayInterval = null;
  let lockEndTime = 0;
  const IDLE_TIMEOUT_MS = 3 * 60 * 1000;

  function updateStatusDisplay() {
    const statusEl = root.querySelector('#aim-backend-status');
    const lockBtn = root.querySelector('#aim-lock-btn');
    if (!statusEl) return;
    const now = Date.now();
    
    if (now < lockEndTime) {
      const remaining = Math.floor((lockEndTime - now) / 1000);
      const m = Math.floor(remaining / 60);
      const s = remaining % 60;
      statusEl.textContent = `STATUS: 🔒 LOCKED WARM (${m}:${s.toString().padStart(2, '0')})`;
      statusEl.style.color = '#ff003c';
      if (lockBtn) lockBtn.style.opacity = '0.5';
    } else if (now < expireTime) {
      const remaining = Math.floor((expireTime - now) / 1000);
      const m = Math.floor(remaining / 60);
      const s = remaining % 60;
      statusEl.textContent = `STATUS: 🔥 WARM (${m}:${s.toString().padStart(2, '0')})`;
      statusEl.style.color = '#ffaa00';
      if (lockBtn) lockBtn.style.opacity = '1';
    } else {
      statusEl.textContent = `STATUS: ❄ COLD BOOT`;
      statusEl.style.color = '#00ffff';
      if (lockBtn) lockBtn.style.opacity = '1';
      if (lockInterval) { clearInterval(lockInterval); lockInterval = null; }
    }
  }

  window._aimNotifyWarm = () => {
    expireTime = Math.max(expireTime, Date.now() + IDLE_TIMEOUT_MS);
    if (!displayInterval) displayInterval = setInterval(() => {
      if (!root.isConnected) {
        clearInterval(displayInterval);
        displayInterval = null;
        return;
      }
      updateStatusDisplay();
    }, 1000);
    updateStatusDisplay();
  };

  root.querySelector('#aim-lock-btn').addEventListener('click', () => {
    if (Date.now() < lockEndTime) return; // Already locked
    if (!confirm('WARNING: Locking the backend prevents it from spinning down for 15 minutes. This will incur consistent compute costs even if idle. Are you sure?')) return;
    
    lockEndTime = Date.now() + (15 * 60 * 1000);
    expireTime = Math.max(expireTime, lockEndTime);
    
    if (lockInterval) clearInterval(lockInterval);
    // Ping every 2 minutes
    lockInterval = setInterval(() => {
      if (!root.isConnected || Date.now() >= lockEndTime) {
        clearInterval(lockInterval);
        lockInterval = null;
        return;
      }
      fetch(`${settings.txt2imgUrl}ping`).catch(()=>{});
      fetch(`${settings.img2imgUrl}ping`).catch(()=>{});
      window._aimNotifyWarm();
    }, 2 * 60 * 1000);
    
    // Initial ping
    fetch(`${settings.txt2imgUrl}ping`).catch(()=>{});
    fetch(`${settings.img2imgUrl}ping`).catch(()=>{});
    
    if (!displayInterval) displayInterval = setInterval(() => {
      if (!root.isConnected) {
        clearInterval(displayInterval);
        displayInterval = null;
        return;
      }
      updateStatusDisplay();
    }, 1000);
    updateStatusDisplay();
  });

  root.querySelector('#aim-shutdown-btn').addEventListener('click', async () => {
    if (lockInterval) { clearInterval(lockInterval); lockInterval = null; }
    lockEndTime = 0;
    expireTime = 0;
    updateStatusDisplay();
    
    try { fetch(`${settings.txt2imgUrl}shutdown`, { method: 'POST' }).catch(()=>{}); } catch(e){}
    try { fetch(`${settings.img2imgUrl}shutdown`, { method: 'POST' }).catch(()=>{}); } catch(e){}
  });

  return root;
}

/* ─── FRAMEPACK PANEL ───────────────────────────────────────── */
function buildFramepack() {
  const currentProfile = (sessionStorage.getItem('current_profile') || 'Guest').toLowerCase();
  const isArchitect = currentProfile === 'archetect' || currentProfile === 'architect' || currentProfile === 'creator' || sessionStorage.getItem('admin_authenticated') === '1';

  const wrap = document.createElement('div');
  wrap.className = 'aim-panel';

  if (isArchitect) {
    wrap.appendChild(buildFramepackContent());
    return wrap;
  }

  // Non-architect profile: Display blurred preview background with public notice stamp
  wrap.innerHTML = `
    <div style="position: relative; width: 100%; min-height: 520px; border-radius: 8px; overflow: hidden; background: #030712;">
      <!-- Blurred Framepack Interface Preview -->
      <div style="filter: blur(8px) brightness(0.35); opacity: 0.5; pointer-events: none; user-select: none; padding: 20px;">
        <div class="aim-panel-header">
          <span class="aim-panel-icon">🎬</span>
          <span class="aim-panel-title">FRAMEPACK STUDIO</span>
          <span class="aim-panel-badge">H100 GPU</span>
        </div>
        <div class="aim-row" style="margin-bottom: 20px;">
          <p style="color: var(--text-muted); font-size: 0.9rem;">
            Framepack Studio requires a dedicated H100 container. Framepack video synthesis engine rendering queue.
          </p>
        </div>
        <div class="aim-row" style="display:flex; gap:10px; justify-content: center; margin-bottom: 20px;">
          <button class="aim-btn" style="padding: 15px 30px; font-size: 1.1rem;">LAUNCH IN BROWSER</button>
          <button class="aim-btn aim-btn-decline" style="padding: 15px 30px; font-size: 1.1rem;">OPEN IN NEW TAB</button>
        </div>
        <div style="width:100%; height:320px; border:1px solid rgba(255,255,255,0.1); border-radius:10px; background: rgba(0,0,0,0.6);"></div>
      </div>

      <!-- Cyberpunk Public Notice Stamp Overlay -->
      <div style="position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; background: rgba(5,8,15,0.75); backdrop-filter: blur(4px); padding: 30px; text-align: center; border: 1px solid rgba(6,182,212,0.4); border-radius: 8px;">
        <div style="font-size: 3rem; margin-bottom: 12px; filter: drop-shadow(0 0 10px rgba(6,182,212,0.6));">🚧</div>
        <h2 class="glitch" data-text="FRAMEPACK STUDIO" style="font-family: 'Orbitron', sans-serif; font-size: 1.6rem; letter-spacing: 2px; color: var(--accent, #06b6d4); margin: 0 0 10px 0;">FRAMEPACK STUDIO</h2>
        
        <div style="background: rgba(255,0,60,0.15); border: 2px solid #ff003c; color: #ff003c; padding: 12px 28px; border-radius: 4px; font-family: 'Orbitron', sans-serif; font-size: 1.05rem; font-weight: bold; letter-spacing: 1.5px; margin-top: 12px; box-shadow: 0 0 25px rgba(255,0,60,0.4); transform: rotate(-1deg); text-transform: uppercase;">
          ⚠️ NOT QUITE READY FOR PUBLIC USE. STAY TUNED!
        </div>

        <p style="color: #aaa; font-family: 'Share Tech Mono', monospace; font-size: 0.85rem; margin-top: 22px; max-width: 460px; line-height: 1.5;">
          Framepack H100 Neural Video Synthesis is restricted during active profile deployment. Full public access will unlock upon model optimization.
        </p>
      </div>
    </div>
  `;

  return wrap;
}

function buildFramepackContent() {
  const inner = document.createElement('div');
  inner.style.width = '100%';
  inner.innerHTML = `
    <div class="aim-panel-header">
      <span class="aim-panel-icon">🎬</span>
      <span class="aim-panel-title">FRAMEPACK STUDIO</span>
      <span class="aim-panel-badge">H100 GPU</span>
    </div>
    <div class="aim-row" style="margin-bottom: 20px;">
      <p style="color: var(--text-muted); font-size: 0.9rem;">
        Framepack Studio requires a dedicated H100 container (cold boot takes ~1-3 minutes).
        Because Gradio cannot be easily rewritten into a static API endpoint, it runs as a full interactive serverless app.
        <br/><br/>
        <strong>Note:</strong> The container will automatically shut down after a period of inactivity to prevent runaway compute costs.
      </p>
    </div>
    <div class="aim-row" style="display:flex; gap:10px; justify-content: center; margin-bottom: 20px;">
      <button class="aim-btn" id="fp-launch-btn" style="padding: 15px 30px; font-size: 1.1rem;">LAUNCH IN BROWSER</button>
      <button class="aim-btn aim-btn-decline" id="fp-newtab-btn" style="padding: 15px 30px; font-size: 1.1rem;">OPEN IN NEW TAB</button>
    </div>
    <div id="fp-frame-container" style="display:none; width:100%; height:800px; border:1px solid var(--border); border-radius:10px; overflow:hidden;">
    </div>
  `;

  const url = 'https://ai-alphacore-tech--framepack-studio-wsl-lifecycle-framep-f935cd.modal.run';

  inner.querySelector('#fp-launch-btn').onclick = () => {
    const container = inner.querySelector('#fp-frame-container');
    container.style.display = 'block';
    container.innerHTML = `<iframe src="${url}" width="100%" height="100%" style="border:none;" allow="camera; microphone; display-capture"></iframe>`;
    if (window._aimNotifyWarm) window._aimNotifyWarm();
  };

  inner.querySelector('#fp-newtab-btn').onclick = () => {
    window.open(url, '_blank');
  };

  return inner;
}