/**
 * IndexedDB handler for the Vision Processor Image Gallery.
 * Saves base64 images generated by the browser directly into a robust local DB.
 */

const DB_NAME = 'AlphaCoreVisionDB';
const DB_VERSION = 1;
const STORE_NAME = 'vision_gallery';

function initVisionDB() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onerror = e => reject(e);
    request.onsuccess = e => resolve(e.target.result);
    request.onupgradeneeded = e => {
      const db = e.target.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        const store = db.createObjectStore(STORE_NAME, { keyPath: 'id', autoIncrement: true });
        store.createIndex('profile', 'profile', { unique: false });
        store.createIndex('timestamp', 'timestamp', { unique: false });
      }
    };
  });
}

export async function saveImageToGallery(profile, prompt, source, data) {
  try {
    const db = await initVisionDB();
    const tx = db.transaction(STORE_NAME, 'readwrite');
    const store = tx.objectStore(STORE_NAME);
    store.add({
      profile: profile || 'UNKNOWN',
      prompt: prompt || 'No prompt provided',
      source: source || 'Unknown Source', 
      data: data, // Base64 data URI or URL
      timestamp: Date.now()
    });
  } catch (e) {
    console.error('[Vision DB] Failed to save image:', e);
  }
}

export async function getAllGalleryImages() {
  return new Promise(async (resolve, reject) => {
    try {
      const db = await initVisionDB();
      const tx = db.transaction(STORE_NAME, 'readonly');
      const store = tx.objectStore(STORE_NAME);
      const req = store.getAll();
      req.onsuccess = () => {
        const sorted = req.result.sort((a,b) => b.timestamp - a.timestamp);
        resolve(sorted);
      };
      req.onerror = e => reject(e);
    } catch (e) {
      reject(e);
    }
  });
}
